library(IPSUR)
install.packages("binom")
library(binom)
pbinom(q = 0, size = 6,prob = 0.4)
pbinom(q = 1, size = 6,prob = 0.4) - pbinom(q = 0, size = 6,prob = 0.4)
pbinom(q = 2, size = 6,prob = 0.4) - pbinom(q = 1, size = 6,prob = 0.4)
pbinom(q = 3, size = 6,prob = 0.4) - pbinom(q = 2, size = 6,prob = 0.4)
pbinom(q = 4, size = 6,prob = 0.4) - pbinom(q = 3, size = 6,prob = 0.4)
pbinom(q = 5, size = 6,prob = 0.4) - pbinom(q = 4, size = 6,prob = 0.4)
pbinom(q = 6, size = 6,prob = 0.4) - pbinom(q = 5, size = 6,prob = 0.4)