x <- c(0,1,2,3,4,5)
prob_x <- c(0.10,0.40,0.20,0.15,0.10,0.05)
k<- c(x*prob_x)
mean <- weighted.mean(x, prob_x)
l <- c((x-mean)*(x-mean))
m <- c(l*prob_x)
variance <- sum(m)
standard_deviation=round(sqrt(variance),2)
cat("mean is",mean)
cat("variance is",variance)
cat("standard deviation is",standard_deviation)
